services:
  app-service:
    build: .

    deploy:
      mode: replicated
      replicas: 6
    labels:
      - "traefik.http.routers.whoami.rule=Host(`pwjs.localhost`)"

  reverse-proxy:
    image: traefik:v3.1
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
